import './global.css';
import { ApplicationContainer } from "@all-in-one/shared-ui"

export const metadata = {
  title: 'Welcome to auth-microfrontend',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ApplicationContainer>{children}</ApplicationContainer>
      </body>
    </html>
  )
}
